package com.textile.dal.hibernate.entity.taka;
// Generated May 16, 2016 11:41:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TakaFlaw generated by hbm2java
 */
@Entity
@Table(name="TAKA_FLAW"
    ,catalog="textile"
)
public class TakaFlaw  implements java.io.Serializable {


     private Integer takaFlawId;
     private int takaId;
     private int flawId;
     private int flawCount;
     private Date lastModified;

    public TakaFlaw() {
    }

    public TakaFlaw(int takaId, int flawId, int flawCount, Date lastModified) {
       this.takaId = takaId;
       this.flawId = flawId;
       this.flawCount = flawCount;
       this.lastModified = lastModified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="taka_flaw_id", unique=true, nullable=false)
    public Integer getTakaFlawId() {
        return this.takaFlawId;
    }
    
    public void setTakaFlawId(Integer takaFlawId) {
        this.takaFlawId = takaFlawId;
    }

    
    @Column(name="taka_id", nullable=false)
    public int getTakaId() {
        return this.takaId;
    }
    
    public void setTakaId(int takaId) {
        this.takaId = takaId;
    }

    
    @Column(name="flaw_id", nullable=false)
    public int getFlawId() {
        return this.flawId;
    }
    
    public void setFlawId(int flawId) {
        this.flawId = flawId;
    }

    
    @Column(name="flaw_count", nullable=false)
    public int getFlawCount() {
        return this.flawCount;
    }
    
    public void setFlawCount(int flawCount) {
        this.flawCount = flawCount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified", nullable=false, length=19)
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


