package com.textile.dal.hibernate.entity.taka;
// Generated May 16, 2016 11:41:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Taka generated by hbm2java
 */
@Entity
@Table(name="TAKA"
    ,catalog="textile"
    , uniqueConstraints = {@UniqueConstraint(columnNames={"beam_id", "beam_taka_no"}), @UniqueConstraint(columnNames="taka_sno")} 
)
public class Taka  implements java.io.Serializable {


     private Integer takaId;
     private int beamId;
     private int beamTakaNo;
     private int takaSno;
     private Long length;
     private Long weight;
     private Date createdOn;
     private String createdBy;
     private Date lastModified;

    public Taka() {
    }

	
    public Taka(int beamId, int beamTakaNo, int takaSno, Date lastModified) {
        this.beamId = beamId;
        this.beamTakaNo = beamTakaNo;
        this.takaSno = takaSno;
        this.lastModified = lastModified;
    }
    public Taka(int beamId, int beamTakaNo, int takaSno, Long length, Long weight, Date createdOn, String createdBy, Date lastModified) {
       this.beamId = beamId;
       this.beamTakaNo = beamTakaNo;
       this.takaSno = takaSno;
       this.length = length;
       this.weight = weight;
       this.createdOn = createdOn;
       this.createdBy = createdBy;
       this.lastModified = lastModified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="taka_id", unique=true, nullable=false)
    public Integer getTakaId() {
        return this.takaId;
    }
    
    public void setTakaId(Integer takaId) {
        this.takaId = takaId;
    }

    
    @Column(name="beam_id", nullable=false)
    public int getBeamId() {
        return this.beamId;
    }
    
    public void setBeamId(int beamId) {
        this.beamId = beamId;
    }

    
    @Column(name="beam_taka_no", nullable=false)
    public int getBeamTakaNo() {
        return this.beamTakaNo;
    }
    
    public void setBeamTakaNo(int beamTakaNo) {
        this.beamTakaNo = beamTakaNo;
    }

    
    @Column(name="taka_sno", unique=true, nullable=false)
    public int getTakaSno() {
        return this.takaSno;
    }
    
    public void setTakaSno(int takaSno) {
        this.takaSno = takaSno;
    }

    
    @Column(name="length", precision=10, scale=0)
    public Long getLength() {
        return this.length;
    }
    
    public void setLength(Long length) {
        this.length = length;
    }

    
    @Column(name="weight", precision=10, scale=0)
    public Long getWeight() {
        return this.weight;
    }
    
    public void setWeight(Long weight) {
        this.weight = weight;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_on", length=19)
    public Date getCreatedOn() {
        return this.createdOn;
    }
    
    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    
    @Column(name="created_by", length=100)
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified", nullable=false, length=19)
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


