package com.textile.dal.hibernate.entity.employee;
// Generated May 16, 2016 11:41:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * EmpAllocation generated by hbm2java
 */
public class EmpAllocation  implements java.io.Serializable {


     private Integer empAllocId;
     private int empId;
     private int machineId;
     private Date lastModified;

    public EmpAllocation() {
    }

    public EmpAllocation(int empId, int machineId, Date lastModified) {
       this.empId = empId;
       this.machineId = machineId;
       this.lastModified = lastModified;
    }
   
    public Integer getEmpAllocId() {
        return this.empAllocId;
    }
    
    public void setEmpAllocId(Integer empAllocId) {
        this.empAllocId = empAllocId;
    }

 
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }

    
    public int getMachineId() {
        return this.machineId;
    }
    
    public void setMachineId(int machineId) {
        this.machineId = machineId;
    }

    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


