package com.textile.dal.hibernate.entity.employee;
// Generated May 16, 2016 11:41:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * EmpAllocation generated by hbm2java
 */
@Entity
@Table(name="EMP_ALLOCATION"
    ,catalog="textile"
)
public class EmpAllocation  implements java.io.Serializable {


     private Integer empAllocId;
     private int empId;
     private int machineId;
     private Date lastModified;

    public EmpAllocation() {
    }

    public EmpAllocation(int empId, int machineId, Date lastModified) {
       this.empId = empId;
       this.machineId = machineId;
       this.lastModified = lastModified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="emp_alloc_id", unique=true, nullable=false)
    public Integer getEmpAllocId() {
        return this.empAllocId;
    }
    
    public void setEmpAllocId(Integer empAllocId) {
        this.empAllocId = empAllocId;
    }

    
    @Column(name="emp_id", nullable=false)
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }

    
    @Column(name="machine_id", nullable=false)
    public int getMachineId() {
        return this.machineId;
    }
    
    public void setMachineId(int machineId) {
        this.machineId = machineId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified", nullable=false, length=19)
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


