package com.textile.dal.hibernate.entity.employee;
// Generated May 16, 2016 11:41:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Employee generated by hbm2java
 */

public class Employee  implements java.io.Serializable {


     private Integer empId;
     private String firstName;
     private String middleName;
     private String lastName;
     private String address;
     private String city;
     private String state;
     private Integer pincode;
     private Date dateOfBirth;
     private String emailId;
     private byte[] identityImage;
     private boolean active;
     private Date lastModified;

    public Employee() {
    }

    public Employee(String firstName, String middleName, String lastName, String address, String city, String state, Integer pincode, Date dateOfBirth, String emailId) {
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.address = address;
        this.city = city;
        this.state = state;
        this.pincode = pincode;
        this.dateOfBirth = dateOfBirth;
        this.emailId = emailId;
    }

    public Employee(Integer empId, boolean active) {
        this.empId = empId;
        this.active = active;
    }
    

    public Integer getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    
    public Integer getPincode() {
        return this.pincode;
    }
    
    public void setPincode(Integer pincode) {
        this.pincode = pincode;
    }


    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }


    public byte[] getIdentityImage() {
        return this.identityImage;
    }
    
    public void setIdentityImage(byte[] identityImage) {
        this.identityImage = identityImage;
    }


    public boolean getActive() {
        return this.active;
    }
    
    public void setActive(boolean active) {
        this.active = active;
    }


    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }

}


