package com.textile.dal.hibernate.entity.beam;
// Generated May 16, 2016 11:41:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Beam generated by hbm2java
 */
@Entity
@Table(name="BEAM"
    ,catalog="textile"
)
public class Beam  implements java.io.Serializable {


     private Integer beamId;
     private int beamSno;
     private int lotId;
     private int machineId;
     private int noOfTaka;
     private Long meterPerTaka;
     private Long totalMeter;
     private Date issueDate;
     private Date completionDate;
     private Date lastModified;

    public Beam() {
    }

	
    public Beam(int beamSno, int lotId, int machineId, int noOfTaka, Date lastModified) {
        this.beamSno = beamSno;
        this.lotId = lotId;
        this.machineId = machineId;
        this.noOfTaka = noOfTaka;
        this.lastModified = lastModified;
    }
    public Beam(int beamSno, int lotId, int machineId, int noOfTaka, Long meterPerTaka, Long totalMeter, Date issueDate, Date completionDate, Date lastModified) {
       this.beamSno = beamSno;
       this.lotId = lotId;
       this.machineId = machineId;
       this.noOfTaka = noOfTaka;
       this.meterPerTaka = meterPerTaka;
       this.totalMeter = totalMeter;
       this.issueDate = issueDate;
       this.completionDate = completionDate;
       this.lastModified = lastModified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="beam_id", unique=true, nullable=false)
    public Integer getBeamId() {
        return this.beamId;
    }
    
    public void setBeamId(Integer beamId) {
        this.beamId = beamId;
    }

    
    @Column(name="beam_sno", nullable=false)
    public int getBeamSno() {
        return this.beamSno;
    }
    
    public void setBeamSno(int beamSno) {
        this.beamSno = beamSno;
    }

    
    @Column(name="lot_id", nullable=false)
    public int getLotId() {
        return this.lotId;
    }
    
    public void setLotId(int lotId) {
        this.lotId = lotId;
    }

    
    @Column(name="machine_id", nullable=false)
    public int getMachineId() {
        return this.machineId;
    }
    
    public void setMachineId(int machineId) {
        this.machineId = machineId;
    }

    
    @Column(name="no_of_taka", nullable=false)
    public int getNoOfTaka() {
        return this.noOfTaka;
    }
    
    public void setNoOfTaka(int noOfTaka) {
        this.noOfTaka = noOfTaka;
    }

    
    @Column(name="meter_per_taka", precision=10, scale=0)
    public Long getMeterPerTaka() {
        return this.meterPerTaka;
    }
    
    public void setMeterPerTaka(Long meterPerTaka) {
        this.meterPerTaka = meterPerTaka;
    }

    
    @Column(name="total_meter", precision=10, scale=0)
    public Long getTotalMeter() {
        return this.totalMeter;
    }
    
    public void setTotalMeter(Long totalMeter) {
        this.totalMeter = totalMeter;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="issue_date", length=19)
    public Date getIssueDate() {
        return this.issueDate;
    }
    
    public void setIssueDate(Date issueDate) {
        this.issueDate = issueDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="completion_date", length=19)
    public Date getCompletionDate() {
        return this.completionDate;
    }
    
    public void setCompletionDate(Date completionDate) {
        this.completionDate = completionDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified", nullable=false, length=19)
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


