/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.ui.beam;


import com.textile.controller.BeamController;
import com.textile.controller.LotController;
import com.textile.controller.MachineController;
import com.textile.ui.img.loader.ImageRenderer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;

/**
 * @author dipuviky
 */
public class FrmBeamList extends javax.swing.JFrame {

    private final BeamController beamController = new BeamController();
    private final LotController lotController = new LotController();
    private final MachineController machineController = new MachineController();
    /**
     * Creates new form FrmBeamReport
     */
    public FrmBeamList() {
        initComponents();
        loadComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scpBeamReport = new javax.swing.JScrollPane();
        tblBeamReport = new javax.swing.JTable();
        pnlSearch = new javax.swing.JPanel();
        lblLotNo = new javax.swing.JLabel();
        cmbMachineNo = new javax.swing.JComboBox<>();
        lblMachineno = new javax.swing.JLabel();
        cmbLotNo = new javax.swing.JComboBox<>();
        btnSearch = new javax.swing.JButton();
        btnIssueNewBeam = new javax.swing.JButton();
        lblHeader = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblBeamReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Lot No", "Machine No", "Beam No", "Issue Date", "E. Taka", "E. Meters", "P. Taka", "P. Meters", "Bal Taka", "Beam Viran", "Viran Date", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBeamReport.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scpBeamReport.setViewportView(tblBeamReport);

        getContentPane().add(scpBeamReport, java.awt.BorderLayout.CENTER);

        pnlSearch.setPreferredSize(new java.awt.Dimension(1244, 70));

        lblLotNo.setText("Lot No");

        cmbMachineNo.setToolTipText("");

        lblMachineno.setText("Machine No");

        cmbLotNo.setToolTipText("");

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search-icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnIssueNewBeam.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIssueNewBeam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add-icon.png"))); // NOI18N
        btnIssueNewBeam.setText("Issue New Beam");
        btnIssueNewBeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueNewBeamActionPerformed(evt);
            }
        });

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Beam Master");

        javax.swing.GroupLayout pnlSearchLayout = new javax.swing.GroupLayout(pnlSearch);
        pnlSearch.setLayout(pnlSearchLayout);
        pnlSearchLayout.setHorizontalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLotNo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbLotNo, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(lblMachineno, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbMachineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIssueNewBeam)
                .addContainerGap())
            .addGroup(pnlSearchLayout.createSequentialGroup()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 1244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );
        pnlSearchLayout.setVerticalGroup(
            pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSearchLayout.createSequentialGroup()
                .addComponent(lblHeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMachineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMachineno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbLotNo, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lblLotNo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIssueNewBeam)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );

        getContentPane().add(pnlSearch, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnIssueNewBeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueNewBeamActionPerformed
        final JDialog frame = new JDialog(this, "Issue New Beam", true);
        FrmBeamIssue frm = new FrmBeamIssue();
        frame.getContentPane().add(frm.getContentPane());
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_btnIssueNewBeamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBeamList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmBeamList().setVisible(true);
        });
    }
    
    private void renderTable() {
        try {
            tblBeamReport.getColumnModel().getColumn(0).setPreferredWidth(50);
            tblBeamReport.getColumnModel().getColumn(1).setPreferredWidth(50);
            tblBeamReport.getColumnModel().getColumn(2).setPreferredWidth(50);
            tblBeamReport.getColumnModel().getColumn(3).setPreferredWidth(60);
            tblBeamReport.getColumnModel().getColumn(tblBeamReport.getColumnCount()-2).setPreferredWidth(20);
            tblBeamReport.getColumnModel().getColumn(tblBeamReport.getColumnCount()-1).setPreferredWidth(20);
            tblBeamReport.getColumnModel().getColumn(tblBeamReport.getColumnCount()-2).setCellRenderer(new ImageRenderer());
            tblBeamReport.getColumnModel().getColumn(tblBeamReport.getColumnCount()-1).setCellRenderer(new ImageRenderer());
        } catch (Exception ex) {
            Logger.getLogger(this.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIssueNewBeam;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbLotNo;
    private javax.swing.JComboBox<String> cmbMachineNo;
    private javax.swing.JLabel lblHeader;
    private javax.swing.JLabel lblLotNo;
    private javax.swing.JLabel lblMachineno;
    private javax.swing.JPanel pnlSearch;
    private javax.swing.JScrollPane scpBeamReport;
    private javax.swing.JTable tblBeamReport;
    // End of variables declaration//GEN-END:variables

    private void loadComponents() {
        try {
            
            renderTable();
            loadLotCombo();
            loadMachineCombo();
        } catch (Exception ex) {
            //TODO : Error
        }
    }

    private void loadLotCombo() throws Exception {
        ComboBoxModel model = new DefaultComboBoxModel(lotController.getLotComboModel("All"));
        cmbLotNo.setModel(model);
    }

    private void loadMachineCombo() throws Exception {
        ComboBoxModel model = new DefaultComboBoxModel(machineController.getMachineComboModel("All"));
        cmbMachineNo.setModel(model);
    }
}