package com.textile.dal.hibernate.entity.machine;
// Generated May 16, 2016 11:41:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Machine generated by hbm2java
 */
@Entity
@Table(name="MACHINE"
    ,catalog="textile"
)
public class Machine  implements java.io.Serializable {


     private Integer machineId;
     private int machineNumber;
     private Date lastModified;

    public Machine() {
    }

    public Machine(int machineNumber, Date lastModified) {
       this.machineNumber = machineNumber;
       this.lastModified = lastModified;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="machine_id", unique=true, nullable=false)
    public Integer getMachineId() {
        return this.machineId;
    }
    
    public void setMachineId(Integer machineId) {
        this.machineId = machineId;
    }

    
    @Column(name="machine_number", nullable=false)
    public int getMachineNumber() {
        return this.machineNumber;
    }
    
    public void setMachineNumber(int machineNumber) {
        this.machineNumber = machineNumber;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified", nullable=false, length=19)
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }




}


