/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.ui;

import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import com.textile.controller.FlawController;

import javax.swing.*;          
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author dipuviky
 */
public class FlawMaster extends javax.swing.JFrame {

    private FlawController flawController = new FlawController();
    private int flawID = 0;
    /**
     * Creates new form NewJFrame
     */
    public FlawMaster() {
        initComponents();
        loadFlawData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        pnlContent = new java.awt.Panel();
        spResult = new javax.swing.JScrollPane();
        tblResult = new javax.swing.JTable();
        pnlOperation = new java.awt.Panel();
        lblFlawName = new java.awt.Label();
        txtFlawName = new java.awt.TextField();
        lblDescription = new java.awt.Label();
        spDescription = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        btnOperation = new javax.swing.JButton();
        lblError = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Flaw Master");

        tblResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblResult.setName("tblResult"); // NOI18N
        tblResult.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblResult.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblResultMouseClicked(evt);
            }
        });
        spResult.setViewportView(tblResult);

        lblFlawName.setText("Flaw Name");

        lblDescription.setText("Description");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        spDescription.setViewportView(txtDescription);

        btnCancel.setActionCommand("Cancel");
        btnCancel.setLabel("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOperation.setLabel("Add");
        btnOperation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOperationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOperationLayout = new javax.swing.GroupLayout(pnlOperation);
        pnlOperation.setLayout(pnlOperationLayout);
        pnlOperationLayout.setHorizontalGroup(
            pnlOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFlawName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFlawName, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlOperationLayout.createSequentialGroup()
                        .addComponent(btnOperation)
                        .addGap(21, 21, 21)
                        .addComponent(btnCancel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOperationLayout.setVerticalGroup(
            pnlOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOperationLayout.createSequentialGroup()
                .addGroup(pnlOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFlawName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFlawName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOperation))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        lblError.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N
        lblError.setForeground(java.awt.Color.red);
        lblError.setText("label1");
        lblError.setVisible(false);

        javax.swing.GroupLayout pnlContentLayout = new javax.swing.GroupLayout(pnlContent);
        pnlContent.setLayout(pnlContentLayout);
        pnlContentLayout.setHorizontalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlContentLayout.createSequentialGroup()
                .addGroup(pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spResult, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
                    .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlContentLayout.setVerticalGroup(
            pnlContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlContentLayout.createSequentialGroup()
                .addComponent(pnlOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spResult, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblError, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHeader, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblResultMouseClicked
    
        btnCancel.doClick();
        System.out.println(tblResult.getSelectedRow() + "  " + tblResult.getSelectedColumn());
        if (tblResult.getSelectedColumn() <= 3) return;
        
        flawID = Integer.parseInt(tblResult.getValueAt(tblResult.getSelectedRow(), 0).toString());
        
        if (tblResult.getSelectedColumn() == 4) {
            btnOperation.setText("Edit");
            txtFlawName.setText(tblResult.getValueAt(tblResult.getSelectedRow(), 1).toString());
            txtDescription.setText(tblResult.getValueAt(tblResult.getSelectedRow(), 2).toString());
        }
        if (tblResult.getSelectedColumn() == 5) {
            int option  = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete flaw ", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            System.out.println("option selected " + option + " id " + flawID);
            if (option == 0) {
                try {
                    flawController.deleteFlaw(flawID);
                    JOptionPane.showMessageDialog(this, "Flaw deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadFlawData();
                } catch (Exception ex) {
                    loadError(ex.getMessage()); 
                    Logger.getLogger(FlawMaster.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
    }//GEN-LAST:event_tblResultMouseClicked

    private void btnOperationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOperationActionPerformed
        clearError();
        if (saveFlaw()) {
            JOptionPane.showMessageDialog(this, "Flaw saved successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
            loadFlawData();
            btnCancel.doClick();
        }
    }//GEN-LAST:event_btnOperationActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearError();
        btnOperation.setText("Add");
        txtFlawName.setText("");
        txtDescription.setText("");
        flawID = 0;
    }//GEN-LAST:event_btnCancelActionPerformed

    private void loadFlawData() {
        try {
            Vector<String> tableHeaders = new Vector<>();
            tableHeaders.add("ID");
            tableHeaders.add("Flaw Name");
            tableHeaders.add("Description");
            tableHeaders.add("Last modified");
            tableHeaders.add("");
            tableHeaders.add("");
            //tableHeaders.add("LastUpdated");
            Vector tableData = flawController.GetFlaws();
            
            tblResult.setModel(new DefaultTableModel(tableData, tableHeaders));
        } catch (Exception ex) {
            loadError(ex.getMessage()); 
            Logger.getLogger(FlawMaster.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private Boolean saveFlaw(){
        if (txtFlawName.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter flaw name", "Error", JOptionPane.ERROR_MESSAGE);
            txtFlawName.requestFocus();
            return false;
        }
        try {
            String flawName = txtFlawName.getText().trim();
            String flawDesc = txtDescription.getText().trim();
            System.out.println(flawID);
            if (0 == flawID)
                flawController.AddFlaw(flawName, flawDesc);
            else {
                flawController.EditFlaw(flawID, flawName, flawDesc);
            }
            return true;
        } catch (Exception ex) {
            loadError(ex.getMessage()); 
            Logger.getLogger(FlawMaster.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        // javax.swing.UIManager.setLookAndFeel(MetalLookAndFeel);
         
        
        try {
           
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlawMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlawMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlawMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlawMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlawMaster().setVisible(true);
            }
        });
        
    }
    
    private void loadError(String message){
        lblError.setText(message);
        lblError.setVisible(true);
    }
    
    private void clearError(){
        lblError.setText("");
        lblError.setVisible(true); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOperation;
    private java.awt.Label lblDescription;
    private java.awt.Label lblError;
    private java.awt.Label lblFlawName;
    private javax.swing.JLabel lblHeader;
    private java.awt.Panel pnlContent;
    private java.awt.Panel pnlOperation;
    private javax.swing.JScrollPane spDescription;
    private javax.swing.JScrollPane spResult;
    private javax.swing.JTable tblResult;
    private javax.swing.JTextArea txtDescription;
    private java.awt.TextField txtFlawName;
    // End of variables declaration//GEN-END:variables
}
