package com.textile.dal.hibernate.entity.flaw;
// Generated May 16, 2016 11:41:18 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * FabricFlaw generated by hbm2java
 */

public class FabricFlaw  implements java.io.Serializable {


     private Integer flawId;
     private String flawName;
     private String flawDesc;
     private Date lastModified;

    public FabricFlaw() {
    }

	
    public FabricFlaw(String flawName) {
        this.flawName = flawName;
    }
    public FabricFlaw(String flawName, String flawDesc) {
       this.flawName = flawName;
       this.flawDesc = flawDesc;
    }
   
    public Integer getFlawId() {
        return this.flawId;
    }
    
    public void setFlawId(Integer flawId) {
        this.flawId = flawId;
    }


    public String getFlawName() {
        return this.flawName;
    }
    
    public void setFlawName(String flawName) {
        this.flawName = flawName;
    }

 
    public String getFlawDesc() {
        return this.flawDesc;
    }
    
    public void setFlawDesc(String flawDesc) {
        this.flawDesc = flawDesc;
    }

    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }
    

}


