/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.ui.dashboard;

import com.textile.ui.FrmFlawMaster;
import com.textile.ui.beam.FrmBeamList;
import com.textile.ui.employee.FrmEmployeeList;
import com.textile.ui.folding.FrmTakaUnit;
import java.awt.Container;
import java.util.HashSet;

/**
 *
 * @author dipuviky
 */
public class FrmMain extends javax.swing.JFrame {
    
    HashSet containerMap =  new HashSet<>();

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContent = new javax.swing.JTabbedPane();
        jToolBar1 = new javax.swing.JToolBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mTaka = new javax.swing.JMenu();
        miShowDirectory = new javax.swing.JRadioButtonMenuItem();
        miTakaHistory = new javax.swing.JMenuItem();
        mMasters = new javax.swing.JMenu();
        miFlaw = new javax.swing.JMenuItem();
        miBeamIssue = new javax.swing.JMenuItem();
        miEmployee = new javax.swing.JMenuItem();
        mReport = new javax.swing.JMenu();
        mAdmin = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gaurav Textiles :: Annapurna ");

        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Navigator", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 13))); // NOI18N
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setText("taka 1");
        jToolBar1.add(jLabel1);

        jLabel2.setText("taka 2");
        jToolBar1.add(jLabel2);

        jLabel3.setText("taka 3");
        jToolBar1.add(jLabel3);

        jLabel4.setText("taka 4");
        jToolBar1.add(jLabel4);

        mTaka.setText("Taka");

        miShowDirectory.setSelected(true);
        miShowDirectory.setText("Working Directory");
        mTaka.add(miShowDirectory);

        miTakaHistory.setText("Taka");
        miTakaHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTakaHistoryActionPerformed(evt);
            }
        });
        mTaka.add(miTakaHistory);

        jMenuBar1.add(mTaka);

        mMasters.setText("Masters");
        mMasters.setToolTipText("Master management");

        miFlaw.setText("Flaw Master");
        miFlaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFlawActionPerformed(evt);
            }
        });
        mMasters.add(miFlaw);

        miBeamIssue.setText("Beam");
        miBeamIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBeamIssueActionPerformed(evt);
            }
        });
        mMasters.add(miBeamIssue);

        miEmployee.setText("Employee");
        miEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miEmployeeActionPerformed(evt);
            }
        });
        mMasters.add(miEmployee);

        jMenuBar1.add(mMasters);

        mReport.setText("Report");
        mReport.setToolTipText("Beam issue");
        jMenuBar1.add(mReport);

        mAdmin.setText("Admin");
        mAdmin.setToolTipText("Beam issue");
        jMenuBar1.add(mAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabContent, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabContent, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miFlawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFlawActionPerformed
        FrmFlawMaster cntFlaw = new FrmFlawMaster();
        tabContent.addTab("Flaw Master", cntFlaw.getContentPane());
    }//GEN-LAST:event_miFlawActionPerformed

    private void miBeamIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBeamIssueActionPerformed
        FrmBeamList cntBeam = new FrmBeamList();
        tabContent.addTab("Beam Stats", cntBeam.getContentPane());
    }//GEN-LAST:event_miBeamIssueActionPerformed

    private void miTakaHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTakaHistoryActionPerformed
        FrmTakaUnit frm = new FrmTakaUnit();
        tabContent.addTab("taka", frm);
    }//GEN-LAST:event_miTakaHistoryActionPerformed

    private void miEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miEmployeeActionPerformed
        FrmEmployeeList cntBeam = new FrmEmployeeList();
        tabContent.addTab("Employee Master", cntBeam.getContentPane());
    }//GEN-LAST:event_miEmployeeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        // javax.swing.UIManager.setLookAndFeel(MetalLookAndFeel);
         
        
        try {
           
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFlawMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFlawMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
              java.util.logging.Logger.getLogger(FrmFlawMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFlawMaster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMain().setVisible(true);
            }
        });
    }
    
    private void addContainerToTab(String title, Container tabContent){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mAdmin;
    private javax.swing.JMenu mMasters;
    private javax.swing.JMenu mReport;
    private javax.swing.JMenu mTaka;
    private javax.swing.JMenuItem miBeamIssue;
    private javax.swing.JMenuItem miEmployee;
    private javax.swing.JMenuItem miFlaw;
    private javax.swing.JRadioButtonMenuItem miShowDirectory;
    private javax.swing.JMenuItem miTakaHistory;
    private javax.swing.JTabbedPane tabContent;
    // End of variables declaration//GEN-END:variables
}
