/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.ui.folding;

/**
 *
 * @author dipuviky
 */
public class FrmPTakaHistory extends javax.swing.JPanel {

    
    /**
     * Creates new form FrmPTakaHistory
     */
    public FrmPTakaHistory() {
        initComponents();
        loadComponenets();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlContent = new javax.swing.JPanel();
        pnlM1 = new javax.swing.JPanel();
        pnlM2 = new javax.swing.JPanel();
        pnlM3 = new javax.swing.JPanel();
        pnlM4 = new javax.swing.JPanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        pnlContent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlContent.setLayout(new java.awt.GridLayout(1, 4));

        pnlM1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlM1.setLayout(new javax.swing.BoxLayout(pnlM1, javax.swing.BoxLayout.LINE_AXIS));
        pnlContent.add(pnlM1);

        pnlM2.setLayout(new javax.swing.BoxLayout(pnlM2, javax.swing.BoxLayout.LINE_AXIS));
        pnlContent.add(pnlM2);

        pnlM3.setLayout(new javax.swing.BoxLayout(pnlM3, javax.swing.BoxLayout.LINE_AXIS));
        pnlContent.add(pnlM3);

        pnlM4.setLayout(new javax.swing.BoxLayout(pnlM4, javax.swing.BoxLayout.LINE_AXIS));
        pnlContent.add(pnlM4);

        jScrollPane1.setViewportView(pnlContent);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlM1;
    private javax.swing.JPanel pnlM2;
    private javax.swing.JPanel pnlM3;
    private javax.swing.JPanel pnlM4;
    // End of variables declaration//GEN-END:variables

    private void loadComponenets() {
        FrmPTakaWorker m1 = new FrmPTakaWorker();
        FrmPTakaWorker m2 = new FrmPTakaWorker();
        FrmPTakaWorker m3 = new FrmPTakaWorker();
        FrmPTakaWorker m4 = new FrmPTakaWorker();
        pnlM1.add(m1);
        pnlM2.add(m2);
        pnlM3.add(m3);
        pnlM4.add(m4);
    }
}
