/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.ui.folding;

/**
 *
 * @author dipuviky
 */
public class FrmPTakaWorker extends javax.swing.JPanel {

    /**
     * Creates new form FrmPTakaWorker
     */
    public FrmPTakaWorker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeader = new javax.swing.JLabel();
        scpTable = new javax.swing.JScrollPane();
        tblContent = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lblHeader.setBackground(new java.awt.Color(204, 204, 204));
        lblHeader.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lblHeader.setForeground(new java.awt.Color(0, 102, 102));
        lblHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHeader.setText("Machine No");
        add(lblHeader, java.awt.BorderLayout.PAGE_START);

        scpTable.setPreferredSize(new java.awt.Dimension(0, 0));

        tblContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "E Date", "Worker 1", "Worker 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Float.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblContent.setCellSelectionEnabled(true);
        tblContent.setShowGrid(true);
        tblContent.getTableHeader().setResizingAllowed(false);
        tblContent.getTableHeader().setReorderingAllowed(false);
        scpTable.setViewportView(tblContent);

        add(scpTable, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblHeader;
    private javax.swing.JScrollPane scpTable;
    private javax.swing.JTable tblContent;
    // End of variables declaration//GEN-END:variables
}
