/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.ui.folding;

/**
 *
 * @author dipuviky
 */
public class FrmTakaUnit extends javax.swing.JPanel {

    /**
     * Creates new form FrmTakaUnit
     */
    public FrmTakaUnit() {
        initComponents();
        loadComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHead = new javax.swing.JPanel();
        pnlCenter = new javax.swing.JPanel();
        tabContent = new javax.swing.JTabbedPane();
        pnlFlaw = new javax.swing.JPanel();
        pnlWorker = new javax.swing.JPanel();
        spWorker = new javax.swing.JSplitPane();
        spCurrent = new javax.swing.JSplitPane();
        pnlLeft = new javax.swing.JPanel();
        pnlRight = new javax.swing.JPanel();
        pnlHistory = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        pnlHead.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlHead.setPreferredSize(new java.awt.Dimension(2, 100));
        pnlHead.setLayout(new javax.swing.BoxLayout(pnlHead, javax.swing.BoxLayout.LINE_AXIS));
        add(pnlHead, java.awt.BorderLayout.NORTH);

        pnlCenter.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnlCenter.setLayout(new javax.swing.BoxLayout(pnlCenter, javax.swing.BoxLayout.X_AXIS));

        pnlFlaw.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        pnlFlaw.setLayout(new javax.swing.BoxLayout(pnlFlaw, javax.swing.BoxLayout.LINE_AXIS));
        tabContent.addTab("Flaw Details", pnlFlaw);

        pnlWorker.setLayout(new javax.swing.BoxLayout(pnlWorker, javax.swing.BoxLayout.LINE_AXIS));

        spWorker.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        spCurrent.setDividerSize(5);

        pnlLeft.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "For Current Taka", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        pnlLeft.setPreferredSize(new java.awt.Dimension(200, 0));
        pnlLeft.setLayout(new javax.swing.BoxLayout(pnlLeft, javax.swing.BoxLayout.LINE_AXIS));
        spCurrent.setLeftComponent(pnlLeft);

        pnlRight.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "For Current Machine", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        pnlRight.setLayout(new javax.swing.BoxLayout(pnlRight, javax.swing.BoxLayout.LINE_AXIS));
        spCurrent.setRightComponent(pnlRight);

        spWorker.setLeftComponent(spCurrent);

        pnlHistory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Machine Worker History", javax.swing.border.TitledBorder.LEADING, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 1, 14))); // NOI18N
        pnlHistory.setPreferredSize(new java.awt.Dimension(12, 150));
        pnlHistory.setLayout(new javax.swing.BoxLayout(pnlHistory, javax.swing.BoxLayout.LINE_AXIS));
        spWorker.setRightComponent(pnlHistory);

        pnlWorker.add(spWorker);

        tabContent.addTab("Worker Details", pnlWorker);

        pnlCenter.add(tabContent);

        add(pnlCenter, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlFlaw;
    private javax.swing.JPanel pnlHead;
    private javax.swing.JPanel pnlHistory;
    private javax.swing.JPanel pnlLeft;
    private javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlWorker;
    private javax.swing.JSplitPane spCurrent;
    private javax.swing.JSplitPane spWorker;
    private javax.swing.JTabbedPane tabContent;
    // End of variables declaration//GEN-END:variables

    private void loadComponents() {
        pnlHead.add(new FrmTakaInfo());
        pnlFlaw.add(new FrmTakaFlaw());
        pnlLeft.add(new FrmPTakaWorker());
        pnlRight.add(new FrmPTakaWorker());
        pnlHistory.add(new FrmPTakaHistory());
        
    }
}
