/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.textile.ui.folding;

import com.textile.controller.FlawController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author dipuviky
 */
public class FrmTakaFlaw extends javax.swing.JPanel {
    FlawController flawController =  new FlawController();
    /**
     * Creates new form FrmTakaFlaw
     */
    public FrmTakaFlaw() {
        initComponents();
        loadComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spFlaw = new javax.swing.JSplitPane();
        scpList = new javax.swing.JScrollPane();
        lstFlaw = new javax.swing.JList<>();
        scpFlaw = new javax.swing.JScrollPane();
        tblFlaw = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        lstFlaw.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstFlaw.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstFlawValueChanged(evt);
            }
        });
        scpList.setViewportView(lstFlaw);

        spFlaw.setLeftComponent(scpList);

        tblFlaw.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                " # ", "Flaw", "Comment", "Delete"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFlaw.getTableHeader().setReorderingAllowed(false);
        scpFlaw.setViewportView(tblFlaw);
        if (tblFlaw.getColumnModel().getColumnCount() > 0) {
            tblFlaw.getColumnModel().getColumn(0).setMinWidth(40);
            tblFlaw.getColumnModel().getColumn(0).setMaxWidth(40);
            tblFlaw.getColumnModel().getColumn(1).setMinWidth(50);
            tblFlaw.getColumnModel().getColumn(2).setMinWidth(100);
            tblFlaw.getColumnModel().getColumn(3).setMinWidth(40);
            tblFlaw.getColumnModel().getColumn(3).setMaxWidth(40);
        }

        spFlaw.setRightComponent(scpFlaw);

        add(spFlaw, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void lstFlawValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstFlawValueChanged
        JOptionPane.showMessageDialog(this, lstFlaw.getSelectedIndex());
    }//GEN-LAST:event_lstFlawValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> lstFlaw;
    private javax.swing.JScrollPane scpFlaw;
    private javax.swing.JScrollPane scpList;
    private javax.swing.JSplitPane spFlaw;
    private javax.swing.JTable tblFlaw;
    // End of variables declaration//GEN-END:variables

    private void loadComponents() {
        try {
            //lstFlaw.setModel(flawController.getFlawItems(""));
        } catch (Exception ex) {
            Logger.getLogger(FrmTakaFlaw.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
